# Generated by Django 5.0.6 on 2024-07-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Flogin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone_number", models.CharField(blank=True, max_length=30)),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("chooes", models.CharField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
