# Generated by Django 5.0.6 on 2024-07-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Flogin", "0002_customuser_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
