# Generated by Django 5.0.6 on 2024-07-05 08:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Flogin", "0003_customuser_is_active_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favorite",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=[], size=None
            ),
        ),
    ]
