# Generated by Django 4.2.9 on 2024-01-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('chooes', models.CharField(max_length=30)),
            ],
        ),
    ]
